[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=6.0"]
build-backend = "setuptools.build_meta"

[project]
name = "SuSSE"
description = "SubSahara Solar Estimation"
readme = "README.md"
requires-python = ">=3.13"
dynamic = ["version", "dependencies"]

[tool.setuptools]
package-dir = {"" = "src"}
packages = { find = { where = ["src"] } }  # Use the correct format for finding packages


[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.setuptools_scm]
# Automatically manage versions based on the SCM (git in your case)
write_to = "src/susse/version.py"
