[tox]
envlist = py311
skipsdist = true

[testenv]
allowlist_externals =
    pytest
setenv =
    PYTHONPATH=.
    SOURCE_FOLDER=src/susse
    TEST_FOLDER=tests
deps =
    -rrequirements.txt
    mypy==1.11.2
    pytest-cov==5.0.0
    pytest-benchmark==4.0.0
    -e .
commands =
    pytest --durations=10 --junitxml=test-results/pytest-results-3.11.xml --benchmark-disable --cov={env:SOURCE_FOLDER} --cov-report=html:test-results/coverage --verbose --capture=no {env:TEST_FOLDER} -vv
    coverage report -m



[flake8]
exclude = 
    .tox,
    *.egg,
select = E,W,F
ignore = W503, F401, F403, F405, E501
max-line-length = 88
extend-ignore = E203
docstring-convention = google
output-file = test-results/flake8_results.txt

[isort]
profile = black 
multi_line_output = 3

[black]
max-line-length = 88
target-version = ['py311']

[mypy]
python_version = 3.11
ignore_missing_imports = true

[testenv:check-format]
deps=
    black==24.8.0
    isort==5.9.3
    flake8==6.1.0
    flake8-black==0.3.6
    interrogate==1.7.0
commands=
    flake8 {env:SOURCE_FOLDER}
    isort --check --profile black {env:SOURCE_FOLDER}
    black {env:SOURCE_FOLDER} --check -t py311 -v
    interrogate -v --exclude '**__init__.py' --fail-under 10 {env:SOURCE_FOLDER}

[testenv:static-analysis]
deps =
    mypy==1.11.2
    -rrequirements.txt
    -e .
commands =
    mypy --config-file=tox.ini --implicit-optional {env:SOURCE_FOLDER}

[testenv:format-imports]
deps= 
    isort==5.9.3
commands=
    isort --profile black {env:SOURCE_FOLDER}
    isort --profile black {env:TEST_FOLDER}

[testenv:format-code]
deps= 
    black==24.8.0
commands=
    black {env:SOURCE_FOLDER} -t py311 -v
    black {env:TEST_FOLDER} -t py311 -v

