[tox]
envlist = py311
skipsdist = true

[testenv]
passenv = SSH_AUTH_SOCK
allowlist_externals = coverage
install_command = pip install -U {opts} {packages}
deps = -rrequirements.txt
setenv = 
        PYTHONPATH=.
        SOURCE_FOLDER = src/
        TEST_FOLDER = tests
commands =
    python setup.py bdist_wheel
    pip install -U -e .
    pytest --profile-svg --durations=10 --junitxml=test-results/pytest-results-3.8.xml --benchmark-disable --cov={env:SOURCE_FOLDER} --cov-report=html:test-results/coverage tests -vv
    coverage report -m 



[flake8]
exclude = 
    .tox,
    *.egg,
    data,
select = E,W,F
ignore = W503, F401, F403, F405, E501
max-line-length = 88
extend-ignore = E203
docstring-convention = google
output-file = test-results/flake8_results.txt

[isort]
profile = black 
multi_line_output = 3

[black]
max-line-length = 88
target-version = ['py311']

[mypy]
python_version = 3.11
ignore_missing_imports = true

[testenv:check-format]
deps=
    black==22.3.0
    isort==5.9.3
    flake8==6.1.0
    flake8-black
    mypy==0.910
    interrogate
commands=
    flake8 {env:SOURCE_FOLDER}
    isort --check --profile black {env:SOURCE_FOLDER}
    black {env:SOURCE_FOLDER} --check -t py311 -v
    interrogate -v --fail-under 10 {env:SOURCE_FOLDER}

[testenv:static-analysis]
install_command = pip install -U {opts} {packages}
deps = -rrequirements.txt
setenv = 
        PYTHONPATH=.
        SOURCE_FOLDER = src
commands =
    python setup.py bdist_wheel
    pip install -U .
    mypy --config-file=tox.ini {env:SOURCE_FOLDER} 

[testenv:format-imports]
deps= 
    isort
commands=
    isort --profile black {env:SOURCE_FOLDER}
    isort --profile black {env:TEST_FOLDER}

[testenv:format-code]
deps= 
    black 
commands=
    black {env:SOURCE_FOLDER} -t py311 -v
    black {env:TEST_FOLDER} -t py311 -v

